Repository GuilhermeABRoncari/cinemenu-api, pull requests merged in 2023-05, with the labels that each got.

#2 [SETUP][#1] - Make a initial setup for java project
  cinemenu-api/.gitignore
  cinemenu-api/build.gradle.kts
  cinemenu-api/gradle/wrapper/gradle-wrapper.jar
  cinemenu-api/gradle/wrapper/gradle-wrapper.properties
  cinemenu-api/gradlew
  cinemenu-api/gradlew.bat
  cinemenu-api/settings.gradle.kts
  cinemenu-api/src/main/java/br/com/cinemenu/cinemenuapi/CinemenuApiApplication.java
  cinemenu-api/src/main/resources/application.properties
  cinemenu-api/src/test/java/br/com/cinemenu/cinemenuapi/CinemenuApiApplicationTests.java
Labels: SETUP

#10 [BUGFIX][#9] - Change root of project
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/index.txt
  src/main/java/br/com/cinemenu/cinemenuapi/CinemenuApiApplication.java
  src/main/resources/application.properties
  src/test/java/br/com/cinemenu/cinemenuapi/CinemenuApiApplicationTests.java
Labels: BUGFIX

#11 [SETUP][#3] - Create commit standardization setup
  .githooks/apply-git-hooks.gradle
  .githooks/commit-msg
  build.gradle.kts
  src/main/java/br/com/cinemenu/cinemenuapi/CineMenuApiApplication.java
  src/test/java/br/com/cinemenu/cinemenuapi/CineMenuApiApplicationTests.java
Labels: SETUP

#12 [SETUP][#4] - config delete branch bot
  .github/delete-merged-branch-config.yml
Labels: SETUP

#13 [SETUP][#6] - add JaCoCo dependece in gradle
  build.gradle.kts
Labels: SETUP

#16 [CI][#8] - Config initial ci
  .github/workflows/actions.yml
  build.gradle.kts
  src/test/java/br/com/cinemenu/cinemenuapi/CineMenuApiApplicationTests.java
Labels: CI

#15 [SETUP][#9] - config env variables
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: SETUP

#22 [TEST][#19] - Config ci percent coverage
  .github/workflows/actions.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/br/com/cinemenu/cinemenuapi/CineMenuApiApplication.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/br/com/cinemenu/cinemenuapi/CineMenuApiApplicationTest.java
  src/test/java/br/com/cinemenu/cinemenuapi/CineMenuApiApplicationTests.java
Labels: TEST
